### ISSUE TITLE
关于concept部分的疑问

### ISSUE THREAD

**Issue by thunderboom** [imJiawen/KEFDA#1]
你好，很荣幸读到你的文章，写的很棒，效果也很好。
我看了论文中用到的数据，比较关注concept的部分。在FewRel中，训练集和验证集根据你的concept映射并没有重叠，这意味着训练集的训练并不能在concept上泛化到验证集；然后我注意到你们的融入了wikidata和umls这两个知识图谱，所以这种concept的关系是通过这两个知识图谱间接得到的吗？如果是这样，是根据什么准则抽取获得包含更多concept关系的kg的呢？谢谢！

**Comment by imJiawen** [comment]
您好，

我不太能理解您的问题，但是我想可能是我表述得不够清晰。

我们所采用的概念kg事先基于UMLS和WikiData构建，属于模型输入的一部分。
在预处理阶段，每个样本都会进行一次概念链接，链接到概念知识图谱中。
训练及推理时，概念级别的kg并不会被更新，而是作为一种先验知识指导实体级别的关系分类。

从直观上来说，概念级别知识图谱所包含的信息是一些比较抽象且笼统的知识，如（蛋白质，影响，细胞功能），这类知识相比于实体级别知识图谱而言更新的频率非常低，且规模也要小得多。

我们的任务主要是对实体之间的关系进行判断，而不是概念之间的关系，概念起到的是指导作用。

如果还有什么疑问，也欢迎您随时提出。

**Comment by thunderboom** [comment]
你好，
很感谢你的回答，似乎是我表达的不清楚。具体而言，我统计了训练集和验证集的实体与概念的链接，发现训练集和测试集的概念是没有重叠的，这种情况，训练集上学到的概念和文本的关系，其实很难泛化到测试集上。因此，我猜测这种泛化能力是通过UMLS和WikiData这两个图谱中的概念关系间接保证的。根据你放出来的数据，triple2id.txt这个文件有12000多条数据，应该是两个图谱放到了一起，但其实无法保证训练集和测试集的概念是否在图谱中一定出现某种联系（直接或者是间接），这个点感觉是个风险。所以，我想问问，你在抽取的时候有什么特别的方式来避免这种风险。

**Comment by imJiawen** [comment]
> 你好，
> 很感谢你的回答，似乎是我表达的不清楚。具体而言，我统计了训练集和验证集的实体与概念的链接，发现训练集和测试集的概念是没有重叠的，这种情况，训练集上学到的概念和文本的关系，其实很难泛化到测试集上。因此，我猜测这种泛化能力是通过UMLS和WikiData这两个图谱中的概念关系间接保证的。根据你放出来的数据，triple2id.txt这个文件有12000多条数据，应该是两个图谱放到了一起，但其实无法保证训练集和测试集的概念是否在图谱中一定出现某种联系（直接或者是间接），这个点感觉是个风险。所以，我想问问，你在抽取的时候有什么特别的方式来避免这种风险。

您好，
在这里所使用的WikiData和UMLS相互独立，虽然我们将这两个图一起做了编码，但是它们之间不存在直接的连边。我们更多关注的是如何利用每个知识图谱内的隐含结构知识，希望模型能够在【通用领域知识图谱】上学会如何使用知识图谱，并将知识图谱的使用方式作为一种在领域间迁移的元信息，应用在【特定领域知识图谱】上。而概念级别知识图谱在这里仅作为一种领域先验知识，为抽取过程提供更多的背景信息。

**Comment by thunderboom** [comment]
明白了。但这样不同领域的概念表示还是可能会存在较大的gap，感觉会有一定的风险，效果可能会对图谱的构建很敏感。这个想法还挺有趣的，关注的是领域内概念间的关系，而不是概念帮助领域迁移。这种情况下，感觉做下特征工程可能会更好的结果。

**Comment by imJiawen** [comment]
谢谢您的评论，希望以后有机会还可以多交流:D
