### ISSUE TITLE
concept-level

### ISSUE THREAD

**Issue by zyDotwei** [imJiawen/KEFDA#2]
您好，这里有两个问题想向您请教一下：
1. 根据论文的描述，构建的wikidata的concept-level图谱有6409个Node，但FewRel训练集映射后的概念只有276个，想问下其他的Node是怎么得到的？ 
2. 文章中说通过concept-level的图谱是通过SPARQL_query_service抽取构建，想问下抽取的条件是什么？

**Comment by imJiawen** [comment]
您好，
1. concept-level KG在训练之前已被构建完成，并进行知识图表示学习。它的node的数量与fewrel中能够链接到的节点数量没有关系。
2. wikidata中存在着一些根节点，我们由根节点向下取子节点，将级联关系以及子节点之间的关系取出，构建ontology。这里会设定向下取的层数等条件，但这部分不属于模型的一部分，因此我们不做详细阐述。您也可以选择其他已有的ontology，或者自行构建图进行训练。
