### ISSUE TITLE
5way-1shot复现结果

### ISSUE THREAD

**Issue by yijunL** [imJiawen/KEFDA#4]
您好，
  非常感谢您精彩的论文和工作。我将源码直接下载到本地配置好数据和其它文件后，将train.sh 中的 K参数设置为1，希望进行5way-1shot的实验，但是跑出来的结果只有80左右，跟论文中的87.81有一定差距，请问这是随机数的原因吗？还是更改实验目标之后需要修改其它的超参数呢？期待您的回复！

**Comment by imJiawen** [comment]
您好，

感谢您的肯定。

Table 4中的结果是基于domain adaptation (DA) challenges中的数据所得出的，详情请见[FewRel 2.0 domain adaptation](https://thunlp.github.io/2/fewrel2_da.html) 以及 [Coda Lab](https://competitions.codalab.org/competitions/27981#results)。

该挑战提供test tasks数据，但未公开test tasks的标签，因此需要在预测之后上传您的预测结果，并在排行榜上获得最终结果。
另一方面，由于测试任务标签未公开，我们的ablation study（即Table 5）在validation tasks上进行。

还有一个可能性是，如果您确认所有实验配置和数据都相同，您可以尝试更新的pytorch版本，有时候不同的版本可能会取得截然不同的效果。

**Comment by yijunL** [comment]
非常感谢您的回复！再请问一下可以提供跑测试集的代码吗？proto_meta模型似乎并不能直接用于测试。

**Comment by imJiawen** [comment]
> 

您好，

这一部分用json包load一下就可以，可以参考训练集的读取方式。不同的是训练集是随机采样，测试集是顺序读取list。

实现代码挺简单的，您看一下数据格式很快就能搞定，不涉及复杂的数据操作。
