### ISSUE TITLE
您好，关于测试集关系类别数量的问题

### ISSUE THREAD

**Issue by qq31415926** [imJiawen/KEFDA#5]
fewrel2.0没有公布测试集的关系类别，所以论文中table2的关于测试集的关系类别数15是如何求出的？

**Comment by imJiawen** [comment]
您好，
[原文](https://aclanthology.org/D19-1649.pdf)里有提到

```In the end, we gather a valid dataset with 25 relations and 100 instances for each relation.```

验证集中有10种关系类别，由此可得测试集有15种。

**Comment by qq31415926** [comment]
哦哦懂了
